FROM wordpress

ENV WORDPRESS_DB_HOST=db
ENV WORDPRESS_DB_NAME=paypro_edd_db
ENV WORDPRESS_DB_USER=paypro_edd_user
ENV WORDPRESS_DB_PASSWORD=paypro

VOLUME /var/www/html
COPY ./.install_edd.sh /.install_edd.sh

RUN apt-get update && apt-get install -y \
        libzip-dev \
        zip \
  && docker-php-ext-install zip